### ISSUE TITLE
Creation of sister repository: COSPweb

### ISSUE THREAD

**Issue by alejandrobodas** [CFMIP/COSPv2.0#21]
This is just to record the process of creation of a new repository that will host the COSP web pages, as discussed in the PMC.
@dustinswales , please can you create a new repository called COSPweb and give me the relevant permissions? Thanks!

**Comment by RobertPincus** [comment]
We’ll do you one better, @alejandrobodas. We invited you to join the CFMIP organization so you can do this yourself. 

A question - maybe it makes sense to have the COSP pages look like CFMIP.github.io (i.e. to be an organization page?)

**Comment by alejandrobodas** [comment]
Thanks @RobertPincus, that's very helpful.
I think having the page as CFMIP.github.io is a good idea. I've created the COSPweb repository, but I will transfer the relevant files and delete that repository.

**Comment by alejandrobodas** [comment]
cfmip.github.io repository created. From now on, all the discussion about web pages should happen there. Closing issue.
