### ISSUE TITLE
The number of actual arguments cannot be greater than the number of dummy arguments.   [COSP_INIT]

### ISSUE THREAD

**Issue by douyoujun** [CFMIP/COSPv2.0#25]
when i compiled make driver_COSP1.4 under build directory, this error appeared.

there are 22 arguments in cosp_interface_v1p4.F90  when call COSP_INIT ,but there 26 arguments in  
COSP_INIT in cosp.F90, the inconsitent arguments number resulted the error:

../cosp-1.4-interface/cosp_interface_v1p4.F90(646): error #6784: The number of actual arguments cannot be greater than the number of dummy arguments.   [COSP_INIT]
       call COSP_INIT(cfg%Lisccp_sim,cfg%Lmodis_sim,cfg%Lmisr_sim,cfg%Lradar_sim,        &
------------^
../cosp-1.4-interface/cosp_interface_v1p4.F90(647): error #6633: The type of the actual argument differs from the type of the dummy argument.   [NPOINTS]
            cfg%Llidar_sim,cfg%Lparasol_sim,cfg%Lrttov_sim,gbx%Npoints,gbx%Nlevels,      &

**Comment by alejandrobodas** [comment]
Hello @douyoujun , thanks for raising this issue. I have reproduced your error, so I can confirm that the v1.4 interface is broken. We don't have specific regression tests for this interface, so it seems that some of the latest developments have introduced changes that are not compatible with the v1.4 interface. We'll have to look into this in more detail before implementing a solution. Is there any specific reason why you are using the v1.4 interface? 

Regards,
Alejandro

**Comment by douyoujun** [comment]
thanks  for your reply, i just followed introduction from  README.md, the make and make driver can run normally, the make driver_COSP1.4 didn't work. 
so i gave my question, the 2.0 is the latest development, i will use this version.




yjdou@ium.cn
 
From: alejandrobodas
Date: 2019-06-10 21:10
To: CFMIP/COSPv2.0
CC: douyoujun; Mention
Subject: Re: [CFMIP/COSPv2.0] The number of actual arguments cannot be greater than the number of dummy arguments. [COSP_INIT] (#25)
Hello @douyoujun , thanks for raising this issue. I have reproduced your error, so I can confirm that the v1.4 interface is broken. We don't have specific regression tests for this interface, so it seems that some of the latest developments have introduced changes that are not compatible with the v1.4 interface. We'll have to look into this in more detail before implementing a solution. Is there any specific reason why you are using the v1.4 interface?
Regards,
Alejandro

**Comment by dustinswales** [comment]
@douyoujun 
The v1.4 interface is intended for users transitioning from COSP1.4 -> COSP2.0. This interface has not been kept up-to-date with recent improvements to COSP2, which is currently at COSPv2.1.3.
So If you are new to COSP, we encourage you to use the latest release of COSP2 and its driver.

Best regards,
Dustin

**Comment by RobertPincus** [comment]
As per comments by @dustinswales on Jun 13, this issue will not be addressed.
