### ISSUE TITLE
Example data for tests do not include any night columns

### ISSUE THREAD

**Issue by brhillman** [CFMIP/COSPv2.0#35]
The example data used for regression testing do not contain any night columns, so currently the regression test does not properly test output fields which should be masked at night (i.e., the passive instrument simulator outputs for ISCCP, MISR, and MODIS). The example input data should then contain at least one column for which `sunlit = 0`. Fix for this coming shortly.

**Comment by brhillman** [comment]
Opening this just to document the issue before submitting a PR to fix.

**Comment by RobertPincus** [comment]
Closed with commit 43a9bd1a17c53744c7d5bfcf260458163ae1c88b, #51 .
