### ISSUE TITLE
Allocation issue with MODIS/Cloudsat joint-products

### ISSUE THREAD

**Issue by dustinswales** [CFMIP/COSPv2.0#39]
@takmichibata 
If these diagnostics are not requested, there is a runtime error as these fields are always allocated.
I propose you add some logic around this section of code, lines 1600-1683 of cosp.F90, so that the diagnostics are produced only when the fields are requested. 
As a reference, see how the joint Cloudsat-Calipso products, just above where your MODIS/Cloudsat joint-diagnostics handle this issue.

**Comment by takmichibata** [comment]
**@dustinswales** 
I apologize for my late reply, and thanks for informing me of this issue via e-mail.
(I did not realize this forum, sorry.)
I’ll check this bug and other reported issues (i.e., #41 and #42) soon.
