### ISSUE TITLE
cosp_diag_warmrain has wrong dimensions for variable frac_out / design flaw

### ISSUE THREAD

**Issue by roj222** [CFMIP/COSPv2.0#41]
The size of the matrix "frac_out" should be (nPoints,nColumns,nLevels) but Nlvgrid is being passed into the subroutine cosp_diag_warmrain as "nLevels" (see cosp.F90 line 1629 and cosp_stats.F90 line 283).   On my system this is causing random values to appear in the additional elements within frac_out and causing "random errors" in the output variable wr_occfreq_ntotal.

I believe there is a design flaw here with the authors of this algorithm assuming that frac_out is based on the same grid as the re-grided radar reflectivity (which it isn't).   I suspect the easiest solution is to pass in the radar reflectivity on the model grid (i.e. using nLevels) rather than using the radar grid (on vgrid) but that may violate the intent to reproduce a CloudSat-specific result and accordingly the algorithm needs to be redesigned to either (a) NOT use frac_out or (b) re-grid frac_out on to CloudSat radar (vgrid).

** NOTE: I have not checked to see if the same problem exists in other routines.   I found this because of my cosp2_test output was generating strange results.

**Comment by takmichibata** [comment]
**@roj222** 
Thank you for your bug report.
Since I have tested the case that nLevels and Nlvgrid are the same, I did not realize this bug in my model configuration.
I'll check the issue soon, and try to fix them.

**Comment by RobertPincus** [comment]
Closed by commit e858e573ffcb159d0b203b37a6d865d3508598b4 to master.
