### ISSUE TITLE
cosp2_test reference (test) output is missing variables & needs versioning. 

### ISSUE THREAD

**Issue by roj222** [CFMIP/COSPv2.0#42]
The cosp2_test driver is producing outputs (all related to ncfodd) which is not in the test dataset currently supplied with the master branch (cosp2_output_um.ref.nc).   I note this test data does not appear to have any versioning information, which is problematic in this regards.

Missing variables are listed below:

< 	float npdfcld(loc) ;
< 		npdfcld:long_name = "# of Non-Precipitating Clouds" ;
< 		npdfcld:units = "1" ;
< 		npdfcld:standard_name = "number_of_slwc_nonprecip" ;
< 	float npdfdrz(loc) ;
< 		npdfdrz:long_name = "# of Drizzling Clouds" ;
< 		npdfdrz:units = "1" ;
< 		npdfdrz:standard_name = "number_of_slwc_drizzle" ;
< 	float npdfrain(loc) ;
< 		npdfrain:long_name = "# of Precipitating Clouds" ;
< 		npdfrain:units = "1" ;
< 		npdfrain:standard_name = "number_of_slwc_precip" ;
< 	float ncfodd1(CFODD_NICOD, CFODD_NDBZE, loc) ;
< 		ncfodd1:long_name = "# of CFODD (05 < Reff < 12 micron)" ;
< 		ncfodd1:units = "1" ;
< 		ncfodd1:standard_name = "cfodd_reff_small" ;
< 	float ncfodd2(CFODD_NICOD, CFODD_NDBZE, loc) ;
< 		ncfodd2:long_name = "# of CFODD (12 < Reff < 18 micron)" ;
< 		ncfodd2:units = "1" ;
< 		ncfodd2:standard_name = "cfodd_reff_medium" ;
< 	float ncfodd3(CFODD_NICOD, CFODD_NDBZE, loc) ;
< 		ncfodd3:long_name = "# of CFODD (18 < Reff < 35 micron)" ;
< 		ncfodd3:units = "1" ;
< 		ncfodd3:standard_name = "cfodd_reff_large" ;
< 	float CFODD_NDBZE(CFODD_NDBZE) ;
< 		CFODD_NDBZE:long_name = "CloudSat+MODIS dBZe vs ICOD joint PDF X-axis" ;
< 		CFODD_NDBZE:units = "dBZ" ;
< 		CFODD_NDBZE:standard_name = "cloudsat_quivalent_reflectivity_factor" ;
< 	float CFODD_NICOD(CFODD_NICOD) ;
< 		CFODD_NICOD:long_name = "CloudSat+MODIS dBZe vs ICOD joint PDF Y-axis" ;
< 		CFODD_NICOD:units = "none" ;
< 		CFODD_NICOD:standard_name = "modis_in-cloud_optical_depth" ;

**Comment by RobertPincus** [comment]
@takmichibata We could resolve this if you would be willing to run the driver that produces the outputs from the warm rain diagnostics (as detailed by @roj222) and use the output to replace the existing reference files used in the comparison. You would then open a pull request asking to update the reference files. In support of this pull request you would provide some figures and/or other scientific validation. Are you able to do this?

**Comment by RobertPincus** [comment]
@takmichibata I encourage you to make a new branch starting from master to address this issue and #39 . Updates to master have automated comparisons against known-good output which will greatly simplify further development.

**Comment by takmichibata** [comment]
**@RobertPincus** 
Thank you for your suggestion. I'll make a new branch from master to work on these issues related to the warm rain diagnostics.
I'll try to fix the bugs.

**@roj222** 
Thank you for your bug report in this regard.
I apologize for the inconvenience in this matter.

**Comment by RobertPincus** [comment]
Resolved by commit 562b7b3feb41a35d9d267832d950ee748d23cbde . Files are not explicitly versioned but are associated with each commit to the repo.
