### ISSUE TITLE
Remove COSPv1.4 interface

### ISSUE THREAD

**Issue by dustinswales** [CFMIP/COSPv2.0#44]
As part of the COSP2 release we provided a "drop-in replacement" interface that would allow COSP1 users to use the new COSP2 code with little interruption on their side. Essentially the role of this interface was to map derived data types (DDTs) used in COSP1 to the DDTs used in COSP2.
This interface was maintained up until COSPv2.0.3,  consistent with the last release of COSP1, v1.4.3.
However, many developments have been added to the COSP2 repository since, the latest version is v2.1.6, and this interface is no longer compatible with these later versions of COSP2, v2.1 and later. Supporting this interface beyond v2.0.3 isn't sensible as the new diagnostics will not be available to users of the COSP1 code base.
We (Robert and I) propose we remove this deprecated code from the current COSP2 code base.

**Comment by alejandrobodas** [comment]
@dustinswales @RobertPincus I think this makes sense, so +1 from me. Given that not everyone watches the repository, it may be worth pointing the PMC to this issue?

**Comment by alejandrobodas** [comment]
@dustinswales I am implementing some changes to address #43 and I have a question regarding CMOR. Is the CMOR implementation still functional or it only works with the v1.4 interface? I am trying  to understand if the CMOR outputs are going to go away with this issue or they will still be retained.

**Comment by RobertPincus** [comment]
I propose we remove the CMOR dependency. This was originally for running off-line, as I recall, and seems not in the spirit of the current code.

**Comment by dustinswales** [comment]
@alejandrobodas 
We said goodbye to CMOR at v2.1, same time we stopped maintaining the v1.4 interface. We replaced the offline driver w/ straight netCDF output.

**Comment by alejandrobodas** [comment]
I had forgotten about that, thanks for the clarification.
