### ISSUE TITLE
Missing type specifier causing crash on Cori-KNL in running debug mode

### ISSUE THREAD

**Issue by whannah1** [CFMIP/COSPv2.0#74]
I've been working with @brhillman to test his update to the COSP interface that was written to work with E3SM-MMF. My test runs run without debug mode, but when I enable debug mode I get a floating point overflow error and a backtrace that points to line 121 of src/simulator/cosp_cloudsat_interface.F90, which looks like this:

    rcfg%step_list(j)=0.1_wp+0.1_wp*((j-1)**1.5)

Adding the "wp" type to the value in the exponent resolves the issue:

    rcfg%step_list(j)=0.1_wp+0.1_wp*((j-1)**1.5_wp)

**Comment by dustinswales** [comment]
@whannah1 Thanks for identifying this issue. I agree that all floating point operations should be in the working precision (_wp). I will add the fix soon.

**Comment by whannah1** [comment]
Thanks, I actually tried to create a PR, but hen I realized I'm not allowed to push branches here. So I appreciate the assist!

**Comment by dustinswales** [comment]
@whannah1 If you want to open a PR, by all mean please do so. You shouldn't need admin privileges to open the PR, just to merge (which is the responsibility of the COSP code managers)

**Comment by whannah1** [comment]
I can open a PR, but I can't seem to create a branch to use for a new PR. Maybe there's a button I'm missing, but I created a local branch and couldn't push it to the repo. I'm probably missing something simple.

**Comment by RobertPincus** [comment]
@whannah1 You can always fork the repo, add a branch to your fork, and open a PR from your repo against the central one.

**Comment by whannah1** [comment]
@RobertPincus thanks for the tip!
